name: Update gist with Monkeytype Personal Bests
on:
  push:
    paths-ignore:
      - '**.md'
    branches:    
      - main
  schedule:
  - cron: "0 */6 * * *"
      
jobs:
  update-gist:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Gist
        run: |
          swift run MonkeytypeBox -o image.jpg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone "https://user:${GH_TOKEN}@gist.github.com/${GIST_TOKEN}.git" gist
          mv image.jpg gist
          cd gist
          git add image.jpg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update image"
            git push origin main
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          MONKEYTYPE_APE_KEY: ${{ secrets.MONKEYTYPE_APE_KEY }}
